### ISSUE TITLE
Create a branch for 4.19 kernel

### ISSUE THREAD

**Issue by gtarsia** [opokatech/i2c-hid-fix#2]
I have a build for 4.19 kernel, but it's probably best if it had it's own branch, can you create the branch so I can target my pull request to it?

Thanks a lot for this repo, my cpu and drive are happier now.

**Comment by opokatech** [comment]
Thanks that it helped. My drive and cpu got also a happier when kernel stopped flooding kern.log with messages..

Regarding branch: I moved source files to 4.18.0, so you can put sources from 4.19 to own folder. The makefile is common so it landed in "common" folder and is linked in 4.xx directories.

Thanks for contributing - I hope this will be solved eventually and this repo will no longer be needed.

**Comment by opokatech** [comment]
Since no branch is needed anymore (just place files in a new folder similarly to 4.18.0) I'm closing the issue.
